### PR TITLE
Alternative for disabled escapeshellarg() function

### PR DESCRIPTION
**Pull request by alvaro-canepa**

### CODE REVIEW

**Comment by Garbee** [comment]
Can we please get some kind of signal as to what should be done here to have this PR merged? It does need a rebase, but other than that are there any tests to be written or questions about the change?

Other projects rely on this which currently doesn't work in some shared hosting environments. This is because for some odd reason they turn off security features. So, it would be nice to have this check in place to function equally in environments with the internal function turned off. As it is, any project depending upon this package doesn't work when `escapeshellarg` is disabled via `php.ini`.

Thank you.

**Comment by Garbee** [comment]
Oh, just realized this is a read-only split. So the commit needs to go into a higher-level repository it looks like.

**Comment by Garbee** [comment]
Looks like [symfony/symfony](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/ProcessUtils.php) is where this should be requested at.

**Comment by nicolas-grekas** [comment]
Closing as this has been already fixed in recent versions, which don't use the function anymore.

**Pull request closed without merging**
